# Generated by Django 2.0.2 on 2023-10-31 15:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='视频名称')),
                ('content', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='视频内容')),
                ('thumb', models.ImageField(blank=True, null=True, upload_to='video_thumb/', verbose_name='缩略图')),
                ('category', models.IntegerField(choices=[(1, '课程'), (2, '考试'), (3, '综合'), (4, '娱乐')], default=1, verbose_name='视频类别')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击量')),
                ('hot_value', models.IntegerField(default=0, verbose_name='热度指数')),
                ('uper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频们',
            },
        ),
    ]
