# Generated by Django 2.0.2 on 2023-10-31 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='作文标题')),
                ('content', models.FileField(blank=True, null=True, upload_to='essays/', verbose_name='作文内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击量')),
                ('hot_value', models.IntegerField(default=0, verbose_name='热度指数')),
            ],
            options={
                'verbose_name': '作文',
                'verbose_name_plural': '作文们',
            },
        ),
    ]
